exclude: 'popclass/data/.*|examples/.*'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.15.0
  hooks:
  -   id: reorder-python-imports
