version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc

sphinx:
  configuration: docs/source/conf.py


formats:
    - pdf
    - epub


python:
    install:
    - requirements: docs/requirements.txt
