name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t popclass
      - name: Run tests
        run: docker run -v .:/popclass/ popclass bash -c "cd /popclass && pytest -v" 

        