name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t popclass
      - name: Tests
        run: |
          ci_env=`bash <(curl -s https://codecov.io/env)`
          docker run -v .:/popclass/ $ci_env -e CI=true popclass bash -c "cd /popclass && pytest -v --cov --cov-report=xml"
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
